version: '3'
services:
  postgres-db:
      image: postgres:13
      container_name: postgres-db
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - 5432:5432